import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'api-reference',
    {
      type: 'category',
      label: '패키지별 API (자동 생성)',
      collapsed: true,
      // docs/api/*.md 자동 수집(gen:api 로 소스 TSDoc 에서 생성). 정렬=각 페이지 sidebar_position.
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    'charting',
    'nextjs-ssr',
    'architecture',
    'comparison',
    {
      type: 'category',
      label: '마이그레이션',
      items: [
        'migration/variant-table',
        'migration/dataTable-migration',
        'migration/deprecated-aliases',
        'migration/incremental-strategy',
        'migration/live-demos',
      ],
    },
  ],
};

export default sidebars;
