// spec Section 2-2
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'architecture',
    { type: 'autogenerated', dirName: 'api' },
  ],
};

export default sidebars;
